In [1]:
import sys
import numpy
numpy.set_printoptions(threshold = sys.maxsize)
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('coronathon.csv')

In [3]:
data

Age  Gender  Loss of smell and taste  Fever  Persistent Cough  \
0       1       1                        0      0                 0   
1       1       1                        0      0                 0   
2       1       1                        0      0                 0   
3       1       1                        0      0                 0   
4       1       1                        0      0                 1   
5       1       1                        0      0                 1   
6       1       1                        0      0                 1   
7       1       1                        0      0                 1   
8       1       1                        0      1                 0   
9       1       1                        0      1                 0   
10      1       1                        0      1                 0   
11      1       1                        0      1                 0   
12      1       1                        0      1                 1   
13      1       1                        0      1                 1   
14      1       1                        0      1                 1   
15      1       1                        0      1                 1   
16      1       1                        1      0                 0   
17      1       1                        1      0                 0   
18      1       1                        1      0                 0   
19      1       1                        1      0                 0   
20      1       1                        1      0                 1   
21      1       1                        1      0                 1   
22      1       1                        1      0                 1   
23      1       1                        1      0                 1   
24      1       1                        1      1                 0   
25      1       1                        1      1                 0   
26      1       1                        1      1                 0   
27      1       1                        1      1                 0   
28      1       1                        1      1                 1   
29      1       1                        1      1                 1   
...   ...     ...                      ...    ...               ...   
5730   90       0                        0      0                 0   
5731   90       0                        0      0                 0   
5732   90       0                        0      0                 1   
5733   90       0                        0      0                 1   
5734   90       0                        0      0                 1   
5735   90       0                        0      0                 1   
5736   90       0                        0      1                 0   
5737   90       0                        0      1                 0   
5738   90       0                        0      1                 0   
5739   90       0                        0      1                 0   
5740   90       0                        0      1                 1   
5741   90       0                        0      1                 1   
5742   90       0                        0      1                 1   
5743   90       0                        0      1                 1   
5744   90       0                        1      0                 0   
5745   90       0                        1      0                 0   
5746   90       0                        1      0                 0   
5747   90       0                        1      0                 0   
5748   90       0                        1      0                 1   
5749   90       0                        1      0                 1   
5750   90       0                        1      0                 1   
5751   90       0                        1      0                 1   
5752   90       0                        1      1                 0   
5753   90       0                        1      1                 0   
5754   90       0             

In [4]:
data.head()

Age  Gender  Loss of smell and taste  Fever  Persistent Cough  \
0    1       1                        0      0                 0   
1    1       1                        0      0                 0   
2    1       1                        0      0                 0   
3    1       1                        0      0                 0   
4    1       1                        0      0                 1   

   Severe Fatigue  Sore Throat      risk Appointment  
0               0            0       low           y  
1               0            1       low           y  
2               1            0       low           y  
3               1            1       low           y  
4               0            0  moderate           n

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5760 entries, 0 to 5759
Data columns (total 9 columns):
Age                        5760 non-null int64
Gender                     5760 non-null int64
Loss of smell and taste    5760 non-null int64
Fever                      5760 non-null int64
Persistent Cough           5760 non-null int64
Severe Fatigue             5760 non-null int64
Sore Throat                5760 non-null int64
risk                       5760 non-null object
Appointment                5760 non-null object
dtypes: int64(7), object(2)
memory usage: 405.1+ KB


In [6]:
data.describe()

Age       Gender  Loss of smell and taste        Fever  \
count  5760.000000  5760.000000              5760.000000  5760.000000   
mean     45.500000     0.500000                 0.500000     0.500000   
std      25.981414     0.500043                 0.500043     0.500043   
min       1.000000     0.000000                 0.000000     0.000000   
25%      23.000000     0.000000                 0.000000     0.000000   
50%      45.500000     0.500000                 0.500000     0.500000   
75%      68.000000     1.000000                 1.000000     1.000000   
max      90.000000     1.000000                 1.000000     1.000000   

       Persistent Cough  Severe Fatigue  Sore Throat  
count       5760.000000     5760.000000  5760.000000  
mean           0.500000        0.500000     0.500000  
std            0.500043        0.500043     0.500043  
min            0.000000        0.000000     0.000000  
25%            0.000000        0.000000     0.000000  
50%            0.500000        0.500000     0.500000  
75%            1.000000        1.000000     1.000000  
max            1.000000        1.000000     1.000000

In [7]:
data.isnull().any()

Age                        False
Gender                     False
Loss of smell and taste    False
Fever                      False
Persistent Cough           False
Severe Fatigue             False
Sore Throat                False
risk                       False
Appointment                False
dtype: bool

In [8]:
data.head(2)

Age  Gender  Loss of smell and taste  Fever  Persistent Cough  \
0    1       1                        0      0                 0   
1    1       1                        0      0                 0   

   Severe Fatigue  Sore Throat risk Appointment  
0               0            0  low           y  
1               0            1  low           y

In [9]:
data['risk'].unique()

array(['low', 'moderate', 'high'], dtype=object)

In [10]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
data['risk'] = le.fit_transform(data['risk'])
data['Appointment'] = le.fit_transform(data['Appointment'])

In [11]:
data.drop(['Appointment'], axis = 1, inplace = True)

In [12]:
data.head(2)

Age  Gender  Loss of smell and taste  Fever  Persistent Cough  \
0    1       1                        0      0                 0   
1    1       1                        0      0                 0   

   Severe Fatigue  Sore Throat  risk  
0               0            0     1  
1               0            1     1

In [13]:
x = data.iloc[:, 0:7].values
y = data.iloc[:, 7:8].values

In [14]:
x

array([[ 1,  1,  0,  0,  0,  0,  0],
       [ 1,  1,  0,  0,  0,  0,  1],
       [ 1,  1,  0,  0,  0,  1,  0],
       [ 1,  1,  0,  0,  0,  1,  1],
       [ 1,  1,  0,  0,  1,  0,  0],
       [ 1,  1,  0,  0,  1,  0,  1],
       [ 1,  1,  0,  0,  1,  1,  0],
       [ 1,  1,  0,  0,  1,  1,  1],
       [ 1,  1,  0,  1,  0,  0,  0],
       [ 1,  1,  0,  1,  0,  0,  1],
       [ 1,  1,  0,  1,  0,  1,  0],
       [ 1,  1,  0,  1,  0,  1,  1],
       [ 1,  1,  0,  1,  1,  0,  0],
       [ 1,  1,  0,  1,  1,  0,  1],
       [ 1,  1,  0,  1,  1,  1,  0],
       [ 1,  1,  0,  1,  1,  1,  1],
       [ 1,  1,  1,  0,  0,  0,  0],
       [ 1,  1,  1,  0,  0,  0,  1],
       [ 1,  1,  1,  0,  0,  1,  0],
       [ 1,  1,  1,  0,  0,  1,  1],
       [ 1,  1,  1,  0,  1,  0,  0],
       [ 1,  1,  1,  0,  1,  0,  1],
       [ 1,  1,  1,  0,  1,  1,  0],
       [ 1,  1,  1,  0,  1,  1,  1],
       [ 1,  1,  1,  1,  0,  0,  0],
       [ 1,  1,  1,  1,  0,  0,  1],
       [ 1,  1,  1,  1,  0,  1,  0],
 

In [15]:
y

array([[1],
       [1],
       [1],
       [1],
       [2],
       [1],
       [2],
       [2],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [2],
       [2],
       [2],
       [0],
       [0],
       [2],
       [2],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [2],
       [2],
       [1],
       [2],
       [2],
       [2],
       [2],
       [0],
       [0],
       [0],
       [1],
       [1],
       [2],
       [2],
       [2],
       [2],
       [0],
       [0],
       [2],
       [2],
       [2],
       [0],
       [2],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [2],
       [1],
       [2],
       [2],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
    

In [16]:
 x.shape

(5760, 7)

In [17]:
y.shape

(5760, 1)

In [20]:
from sklearn.preprocessing import OneHotEncoder
oh = OneHotEncoder()
z=oh.fit_transform(y[:,0:1]).toarray()

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [21]:
z

array([[0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [22]:
y=np.delete(y,[0],axis=1) 

In [23]:
y=np.concatenate((z,y),axis = 1)

In [24]:
y.shape

(5760, 3)

In [25]:
data.head()

Age  Gender  Loss of smell and taste  Fever  Persistent Cough  \
0    1       1                        0      0                 0   
1    1       1                        0      0                 0   
2    1       1                        0      0                 0   
3    1       1                        0      0                 0   
4    1       1                        0      0                 1   

   Severe Fatigue  Sore Throat  risk  
0               0            0     1  
1               0            1     1  
2               1            0     1  
3               1            1     1  
4               0            0     2

In [26]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [27]:
x_test.shape

(1152, 7)

In [28]:
x_train.shape

(4608, 7)

In [29]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


LOGISTIC REGRESSION

In [30]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(random_state = 0)# random _state=0 is for consistency...to use the same set every time we run the program
classifier.fit(x_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=0,
            splitter='best')

In [31]:
decisiontree = classifier.predict(x_test)

In [32]:
decisiontree

array([[0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0

In [33]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test,decisiontree)

In [34]:
accuracy

0.9895833333333334

In [35]:
data.head(15)

Age  Gender  Loss of smell and taste  Fever  Persistent Cough  \
0     1       1                        0      0                 0   
1     1       1                        0      0                 0   
2     1       1                        0      0                 0   
3     1       1                        0      0                 0   
4     1       1                        0      0                 1   
5     1       1                        0      0                 1   
6     1       1                        0      0                 1   
7     1       1                        0      0                 1   
8     1       1                        0      1                 0   
9     1       1                        0      1                 0   
10    1       1                        0      1                 0   
11    1       1                        0      1                 0   
12    1       1                        0      1                 1   
13    1       1                        0      1                 1   
14    1       1                        0      1                 1   

    Severe Fatigue  Sore Throat  risk  
0                0            0     1  
1                0            1     1  
2                1            0     1  
3                1            1     1  
4                0            0     2  
5                0            1     1  
6                1            0     2  
7                1            1     2  
8                0            0     1  
9                0            1     1  
10               1            0     0  
11               1            1     0  
12               0            0     0  
13               0            1     0  
14               1            0     0

In [36]:
y_pre = classifier.predict(sc.transform([[1,1,0,0,1,1,1]]))

In [37]:
y_pre

array([[0., 0., 1.]])

In [38]:
y_pre = classifier.predict(sc.transform([[65,1,1,0,0,0,0]]))

In [39]:
y_pre

array([[0., 1., 0.]])

In [40]:
import pickle
pickle.dump(classifier,open('covidrisk.pkl','wb'))

In [41]:
import pickle
pickle.dump(sc,open('scalar.pkl','wb'))